### ISSUE TITLE
iOS - support for 64-bit architectures

### ISSUE THREAD

**Issue by griter** [sharpred/localeSwitcher#1]
Please provide support for 64-bit architectures according to Apple requirements:
https://developer.apple.com/news/?id=10202014a

**Comment by sharpred** [comment]
I am not using or maintaining this module anymore.  Feel free to fork/fix yourself

**Comment by sharpred** [comment]
this project was a sample project linked to the com.sharourideas.locale module which I did not write.  It is not the module itself, so I will be not be fixing it.
