### ISSUE TITLE
Can't install using gittio

### ISSUE THREAD

**Issue by aliaziada** [sharpred/localeSwitcher#2]
Thanks for making this module

When I try to install the module using gittio I get the following error message:

gittio install -p android com.shareourideas.locale
[INFO]  com.shareourideas.locale searching...
[ERROR] com.shareourideas.locale:commonjs no distributable available
[ERROR] com.shareourideas.locale:android no distributable available

**Comment by sharpred** [comment]
this project was a sample project linked to the com.sharourideas.locale module which I did not write.  It is not the module itself, so this is not what is failing on gittio.  You should raise this with the maintainers of the module
